### PR TITLE
Fix tracing propagation for host_calls (fixes #590)

### LINKED ISSUE #590: [BUG] Traces are cut off when an actor calls a provider
**Describe the bug**

Before `v0.62` we used to hold a trace ID in the ActorModule GenServer which we used to reconstitute trace context when an actor called `__host_call` for a provider invocation. In v0.62.0-rc.1 testing, I noticed we don't do that anymore and traces are cut off at that point.

**To Reproduce**

1. Run the OTEL things inside of the `otel` folder in this repo
1. Run the v0.62 release connected to those OTEL resources
1. Run the kvcounter example
2. curl kvcounter
3. Look at tempo at http://localhost:5050 and see 2 traces, one for httpserver -> actor and one for actor -> kvredis

**Expected behavior**

**Environment (please complete the following information)**
 - OS: [e.g. Linux, MacOS, Windows] MacOS
 - Arch: [e.g. x86_64, aarch64] aarch64
 - wasmCloud Version: [e.g. 0.51.0] v0.62.0-rc.1

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Fixes #590 

More information will follow once the wasmcloud/wasmcloud PR merges as implementation may change

## Feature or Problem
This PR uses the updated wasmcloud library (https://github.com/wasmCloud/wasmCloud/pull/298) to propagate the `span_ctx` through the entire invocation chain, ensuring that we are reconnecting traces when actors do a host_call.

## Related Issues
#590 

## Release Information
v0.62.0

## Consumer Impact
Traces work as expected

## Testing

Built on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [x] aarch64-darwin
- [ ] x86_64-windows

### Manual Verification
While testing the runtime I was able to verify this connects host calls in tracing

### CODE REVIEW

File: host_core/lib/host_core/wasmcloud/runtime_server.ex [hunk 1]
```diff
@@ -122,13 +125,24 @@ defmodule HostCore.WasmCloud.Runtime.Server do
 
   @impl true
   def handle_info(
-        {:invoke_callback, claims, binding, namespace, operation, payload, token},
+        {:invoke_callback, claims, {binding, namespace, operation}, payload, call_context, token},
```
Comment (brooksmtownsend) [inline host_core/lib/host_core/wasmcloud/runtime_server.ex:128]: Note that changing this to a tuple was purely to avoid a Rustler issue where there's a macro that doesn't seem to be implemented for 8 arguments. Happy to change the tuple format if desired

Comment (autodidaddict) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:128]: I like this and it's a pinch more idiomatic Elixir to bundle up args into a logically grouped tuple

File: host_core/lib/host_core/wasmcloud/runtime_server.ex [hunk 2]
```diff
@@ -122,13 +125,24 @@ defmodule HostCore.WasmCloud.Runtime.Server do
...
         {_runtime, config} = state
       ) do
     Task.Supervisor.start_child(RuntimeCallSupervisor, fn ->
       # This callback is invoked by the wasmcloud::Runtime's host call handler
       payload = payload |> IO.iodata_to_binary()
 
+      with true <- is_list(call_context),
+           ctx_list <- :erlang.list_to_binary(call_context),
```
Comment (autodidaddict) [inline host_core/lib/host_core/wasmcloud/runtime_server.ex:136]: this with statement is already a bit difficult to understand. if `ctx_list` is actually a binary, should we maybe call it `ctx_binary` instead?

**Review by autodidaddict — CHANGES_REQUESTED** [review]

File: host_core/lib/host_core/wasmcloud/runtime_server.ex (hunk 2 above)
Comment (brooksmtownsend) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:136]: Sure 👍🏻

File: host_core/lib/host_core/wasmcloud/runtime_server.ex [hunk 3]
```diff
@@ -132,10 +132,11 @@ defmodule HostCore.WasmCloud.Runtime.Server do
       # This callback is invoked by the wasmcloud::Runtime's host call handler
       payload = payload |> IO.iodata_to_binary()
 
+      # Convert the `call_context` list of bytes to the `span_ctx` term
       with true <- is_list(call_context),
-           ctx_list <- :erlang.list_to_binary(call_context),
-           true <- is_binary(ctx_list),
-           span_ctx <- :erlang.binary_to_term(ctx_list) do
+           ctx_binary <- :erlang.list_to_binary(call_context),
+           true <- is_binary(ctx_binary),
```
Comment (autodidaddict) [inline host_core/lib/host_core/wasmcloud/runtime_server.ex:138]: potentially superfluous question - doesn't `:erlang.list_to_binary` always return a bitstring value ? If so, do we need the `true <- is_binary(ctx_binary)` guard?

Comment (autodidaddict) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:138]: https://www.erlang.org/doc/man/erlang.html#list_to_binary-1 this looks like it doesn't allow non-binary output

Comment (brooksmtownsend) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:138]: I think so, I was really just being overly cautious

Comment (brooksmtownsend) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:138]: These functions either work or panic so I wanted to ensure we were going down the proper path with the `with`

Comment (autodidaddict) [reply host_core/lib/host_core/wasmcloud/runtime_server.ex:138]: ok it looks like this is "with safe" (e.g. no panic, just match fail).

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iolist term

    :erlang.list_to_binary(nil)
    iex:1: (file)
iex(1)> :erlang.list_to_binary([])
""
iex(2)> :erlang.list_to_binary([65, 66, 67])
"ABC"
iex(3)>
```

**Review by autodidaddict — APPROVED** [review]

**Review by autodidaddict — APPROVED** [review]
:seal:
