### PR TITLE
fix double host stop event 

### LINKED ISSUE #469: [BUG] A stopped host publishes two host_stopped events
**Describe the bug**

When you stop a wasmCloud host, it publishes two `host_stopped` events in the process of shutting down. With the [lattice-observer](https://github.com/wasmCloud/lattice-observer), this can end up double-handling the same event which is unnecessary

**To Reproduce**

1. Start a wasmcloud host
2. Use the NATS CLI to subscribe to `wasmbus.evt.*`
3. Stop it with `./bin/wasmcloud_host stop`
4. Observe two host_stopped events

**Expected behavior**

I'd expect a single `host_stopped` event to be published

### PR DESCRIPTION
**Pull request by giusdp**
This PR fixes #469 

The virtual_host.ex `handle_cast(:do_stop, _timeout_ms}, state)` function invokes `do_purge` and `publish_host_stopped`, then it returns the tuple `{:stop, :shutdown, state}`  triggering the `terminate\2` function.

In `terminate` those two functions are invoked again resulting in a double `host_stopped` event and a double purging of the processes (visible in the logs).

It should be enough not calling those functions immediately in the handle cast but letting `terminate` handle it.

### CODE REVIEW

File: host_core/lib/host_core/vhost/virtual_host.ex [hunk 1]
```diff
@@ -427,9 +427,6 @@ defmodule HostCore.Vhost.VirtualHost do
   def handle_cast({:do_stop, _timeout_ms}, state) do
     Logger.debug("Host stop requested manually")
 
-    do_purge(state)
-    publish_host_stopped(state)
-
```
Comment (brooksmtownsend) [inline host_core/lib/host_core/vhost/virtual_host.ex:432]: We may want to remove the `publish_host_stopped` call, but the `do_purge` is important since it instructs all providers to shutdown with some time to handle cleaning up state and things

**Review by brooksmtownsend — CHANGES_REQUESTED** [review]

File: host_core/lib/host_core/vhost/virtual_host.ex (hunk 1 above)
Comment (brooksmtownsend) [reply host_core/lib/host_core/vhost/virtual_host.ex]: Ah I see what you mean, that function ends up triggering the process termination. I think I misunderstood the change, and you are likely correct that both of those should be gone. Have you been able to test this either way with something like `nats sub wasmbus.evt.*` to listen for host_stopped events?

Comment (giusdp) [reply host_core/lib/host_core/vhost/virtual_host.ex:417]: I've re-added the `do_purge` removal. I checked with `iex -S mix` and `wash ctl stop` listening for the events and the host_stopped event appears only once. In the iex logs the purging works normally too.

**Review by brooksmtownsend — APPROVED** [review]

**Comment by brooksmtownsend** [comment]
@giusdp sorry to bother you, I think the only thing we need here is a rebase and we're good to merge!

**Review by brooksmtownsend — APPROVED** [review]

**Comment by brooksmtownsend** [comment]
Thanks for your patience @giusdp !
